# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

xcode_version:
  - 8.0
  - 8.1
  - 8.2
  - 8.3.3
  - 9.0
target:
  - osx
  - docs
  - ios-static
  - ios-dynamic
  - ios-swift
  - osx-swift
  - watchos
  - cocoapods
  - swiftlint
  - tvos
  - osx-encryption
  - osx-object-server

  - ios-device-objc-ios8
  # - ios-device-swift-ios8
  - ios-device-objc-ios10
  # - ios-device-swift-ios10
  - tvos-device
configuration:
  - Debug
  - Release

# Combinations have to be excluded in a way that's hard to read.
# This table shows which jobs will run:

# +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
# | Configuration Matrix | osx | docs | ios-static | ios-dynamic | ios-swift | osx-swift | watchos | cocoapods | swiftlint | tvos | osx-encryption | osx-object-server | ios-device-objc-ios8 | ios-device-swift-ios8 | ios-device-objc-ios10 | ios-device-swift-ios10 | tvos-device |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | --------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 8.0   | Debug        | X   |      |            |             |           |           |         |           |           |      |                |                   |                      |                       |                       |                        |             |
# | 8.0   | Release      | X   |      | X          | X           | X         | X         | X       | X         |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | --------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 8.1   | Debug        | X   |      |            |             |           |           |         |           |           |      |                |                   |                      |                       |                       |                        |             |
# | 8.1   | Release      | X   |      | X          | X           | X         | X         | X       | X         |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | --------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 8.2   | Debug        | X   |      | X          |             |           |           |         |           |           |      |                |                   |                      |                       |                       |                        |             |
# | 8.2   | Release      | X   |      | X          | X           | X         | X         | X       | X         |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | --------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 8.3.3 | Debug        | X   |      |            | X           | X         | X         | X       |           |           | X    |                |                   |                      |                       |                       |                        |             |
# | 8.3.3 | Release      | X   | X    |            | X           | X         | X         | X       | X         | X         | X    | X              | X                 | X                    |                       | X                     |                        | X           |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | --------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 9.0   | Debug        | X   |      |            | X           | X         | X         | X       |           |           | X    |                |                   |                      |                       |                       |                        |             |
# | 9.0   | Release      | X   |      |            | X           | X         | X         | X       | X         | X         | X    | X              | X                 | X                    |                       | X                     |                        | X           |
# +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

exclude:
  ################
  # docs
  ################
  # Just run on 8.3.3 Release
  - xcode_version: 8.0
    target: docs
  - xcode_version: 8.1
    target: docs
  - xcode_version: 8.2
    target: docs
  - xcode_version: 9.0
    target: docs
  - target: docs
    configuration: Debug

  ################
  # ios-static
  ################
  # Skip on 8.0/8.1 Debug
  # Skip 8.3.3/9.0 altogether since it doesn't support the iOS 7 deployment target
  - xcode_version: 8.0
    target: ios-static
    configuration: Debug
  - xcode_version: 8.1
    target: ios-static
    configuration: Debug
  - xcode_version: 8.3.3
    target: ios-static
  - xcode_version: 9.0
    target: ios-static

  ################
  # ios-dynamic
  ################
  # Skip on 8.0/8.1/8.2 Debug
  - xcode_version: 8.0
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 8.1
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 8.2
    target: ios-dynamic
    configuration: Debug

  ################
  # ios-swift
  ################
  # Skip 8.0/8.1/8.2 Debug
  - xcode_version: 8.0
    target: ios-swift
    configuration: Debug
  - xcode_version: 8.1
    target: ios-swift
    configuration: Debug
  - xcode_version: 8.2
    target: ios-swift
    configuration: Debug

  ################
  # osx-swift
  ################
  # Skip 8.0/8.1/8.2 Debug
  - xcode_version: 8.0
    target: osx-swift
    configuration: Debug
  - xcode_version: 8.1
    target: osx-swift
    configuration: Debug
  - xcode_version: 8.2
    target: osx-swift
    configuration: Debug

  ################
  # watchos
  ################
  # Skip 8.0/8.1/8.2 Debug
  - xcode_version: 8.0
    target: watchos
    configuration: Debug
  - xcode_version: 8.1
    target: watchos
    configuration: Debug
  - xcode_version: 8.2
    target: watchos
    configuration: Debug

  ################
  # cocoapods
  ################
  # Skip Debug
  - target: cocoapods
    configuration: Debug

  ################
  # swiftlint
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: swiftlint
  - xcode_version: 8.1
    target: swiftlint
  - xcode_version: 8.2
    target: swiftlint
  - target: swiftlint
    configuration: Debug

  ################
  # tvos
  ################
  # Skip 8.0/8.1/8.2 Debug
  - xcode_version: 8.0
    target: tvos
    configuration: Debug
  - xcode_version: 8.1
    target: tvos
    configuration: Debug
  - xcode_version: 8.2
    target: tvos
    configuration: Debug

  ################
  # osx-encryption
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: osx-encryption
  - xcode_version: 8.1
    target: osx-encryption
  - xcode_version: 8.2
    target: osx-encryption
  - target: osx-encryption
    configuration: Debug

  ################
  # osx-object-server
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: osx-object-server
  - xcode_version: 8.1
    target: osx-object-server
  - xcode_version: 8.2
    target: osx-object-server
  - target: osx-object-server
    configuration: Debug

  ################
  # ios-device-objc-ios8
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: ios-device-objc-ios8
  - xcode_version: 8.1
    target: ios-device-objc-ios8
  - xcode_version: 8.2
    target: ios-device-objc-ios8
  - target: ios-device-objc-ios8
    configuration: Debug

  ################
  # ios-device-swift-ios8
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: ios-device-swift-ios8
  - xcode_version: 8.1
    target: ios-device-swift-ios8
  - xcode_version: 8.2
    target: ios-device-swift-ios8
  - target: ios-device-swift-ios8
    configuration: Debug

  ################
  # ios-device-objc-ios10
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: ios-device-objc-ios10
  - xcode_version: 8.1
    target: ios-device-objc-ios10
  - xcode_version: 8.2
    target: ios-device-objc-ios10
  - target: ios-device-objc-ios10
    configuration: Debug

  ################
  # ios-device-swift-ios10
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: ios-device-swift-ios10
  - xcode_version: 8.1
    target: ios-device-swift-ios10
  - xcode_version: 8.2
    target: ios-device-swift-ios10
  - target: ios-device-swift-ios10
    configuration: Debug

  ################
  # tvos-device
  ################
  # Just run on 8.3.3/9.0 Release
  - xcode_version: 8.0
    target: tvos-device
  - xcode_version: 8.1
    target: tvos-device
  - xcode_version: 8.2
    target: tvos-device
  - target: tvos-device
    configuration: Debug
