included:
  - Realm/ObjectServerTests
  - RealmSwift
  - Realm/Swift
identifier_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0
  excluded:
    - _addNotificationBlock(_:)
    - _nsError
    - _nsErrorDomain
    - _realmObjectName()
    - id
    - pk
    - to
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - line_length
  - vertical_whitespace
  - syntactic_sugar
  - block_based_kvo
