use_frameworks!

abstract_target 'Demo' do
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm', :git => 'https://github.com/RxSwiftCommunity/RxRealm.git', :tag => '0.4.1'
  pod 'RxRealmDataSources', :path => '../'

  target 'RxRealmDataSources_Example'
  target 'RxRealmDataSources_MacExample'
  target 'RxRealmDataSources_Tests'
end
