use_frameworks!

abstract_target 'Demo' do
  pod 'RealmSwift', '~> 2.1'
  pod 'RxSwift', '~> 3.1'
  pod 'RxCocoa', '~> 3.1'
  pod 'RxRealm', '~> 0.5'
  pod 'RxRealmDataSources', :path => '../'

  target 'RxRealmDataSources_Example' do
    platform :ios, '9.0'
  end

  target 'RxRealmDataSources_MacExample' do
    platform :osx, '10.12'
  end

  target 'RxRealmDataSources_Tests'
end
